import gradio as gr
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.schema import Document
import os
from dotenv import load_dotenv
# No need for re module if we read plain markdown

load_dotenv()

# Define paths
PDF_PATH = "data/gemini-2.5-tech_1-2.pdf"
PARSED_MD_PATH = "llamaparse_output_gemini_1_2.md" # This file needs to be generated by LlamaParse first

# 1. Function to read the markdown file
def get_text_from_markdown(file_path=PARSED_MD_PATH):
    """Reads the markdown file, generating it from PDF if not found."""
    if not os.path.exists(file_path):
        print(f"'{file_path}' not found. Attempting to parse PDF with LlamaParse...")
        api_key = os.getenv("LLAMA_CLOUD_API_KEY")
        if not api_key:
            return "Error: LLAMA_CLOUD_API_KEY not found. Please set it in your .env file."
        try:
            from llama_parse import LlamaParse # Import here to avoid circular dependency if not needed
            from langchain.schema import Document # Import here
            parser = LlamaParse(result_type="markdown", api_key=api_key)
            documents = parser.load_data(PDF_PATH)
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write("\n".join([doc.text for doc in documents]))
            print(f"Successfully parsed PDF and saved to '{file_path}'")
        except Exception as e:
            return f"LlamaParse processing error: {e}"
            
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
        return content
    except Exception as e:
        return f"An error occurred while reading the file: {e}"

# 2. Main function to split the text and visualize
def visualize_splitting(parent_chunk_size, parent_chunk_overlap, child_chunk_size, child_chunk_overlap):
    """
    Loads text, splits it into parent and child chunks,
    and returns a markdown visualization.
    """
    # Load the text
    source_text = get_text_from_markdown()
    if source_text.startswith("Error:"):
        return source_text

    # Initialize splitters
    parent_splitter = RecursiveCharacterTextSplitter(
        chunk_size=parent_chunk_size,
        chunk_overlap=parent_chunk_overlap
    )
    child_splitter = RecursiveCharacterTextSplitter(
        chunk_size=child_chunk_size,
        chunk_overlap=child_chunk_overlap
    )

    # Create parent documents
    parent_docs = parent_splitter.create_documents([source_text])

    # Prepare markdown output
    markdown_output = [f"# Chunk Visualization Result for {PARSED_MD_PATH}"]

    if not parent_docs:
        markdown_output.append("No parent chunks were created. Try adjusting the chunk size.")
        return "\n".join(markdown_output)

    for i, doc in enumerate(parent_docs):
        # Add parent chunk info
        markdown_output.append(f"\n---\n## Parent Chunk {i + 1}\n")
        markdown_output.append(f"**Size:** {len(doc.page_content)} characters")
        markdown_output.append("```")
        markdown_output.append(doc.page_content)
        markdown_output.append("```")

        # Create and add child chunks info
        child_docs = child_splitter.create_documents([doc.page_content])
        if child_docs:
            markdown_output.append(f"\n### Child Chunks for Parent {i + 1}\n")
            for j, child_doc in enumerate(child_docs):
                markdown_output.append(f"#### Child {j + 1}")
                markdown_output.append(f"**Size:** {len(child_doc.page_content)} characters")
                markdown_output.append("```")
                markdown_output.append(child_doc.page_content)
                markdown_output.append("```")
        else:
            markdown_output.append("\n*No child chunks created for this parent.*")


    return "\n".join(markdown_output)

# 3. Gradio Interface
with gr.Blocks(theme="soft", css="h1, h2, h3, h4 {font-weight: bold;}") as demo:
    gr.Markdown(f"# LangChain Text Splitter Visualizer for {PDF_PATH}")
    gr.Markdown(
        f"This app visualizes how `RecursiveCharacterTextSplitter` divides text from `{PARSED_MD_PATH}` "
        "into parent and child chunks based on your settings."
    )

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("### Parent Splitter Settings")
            p_chunk_size = gr.Number(label="Chunk Size", value=2000)
            p_chunk_overlap = gr.Number(label="Chunk Overlap", value=200)

        with gr.Column(scale=1):
            gr.Markdown("### Child Splitter Settings")
            c_chunk_size = gr.Number(label="Chunk Size", value=400)
            c_chunk_overlap = gr.Number(label="Chunk Overlap", value=40)

    process_btn = gr.Button("Run Splitter Visualization", variant="primary")

    output_display = gr.Markdown(label="Visualization Output")

    process_btn.click(
        fn=visualize_splitting,
        inputs=[p_chunk_size, p_chunk_overlap, c_chunk_size, c_chunk_overlap],
        outputs=[output_display]
    )

demo.launch()
